server:
  port: 5001
spring:
  cloud:
    config:
      server:
        native
        git:
          uri: https://github.com/xayouyue/Microservices
          search-paths: ConfigLocation
          username: sky.jiang.s.z@gmail.com
          password: jsz_6373
